In [1]:
import numpy as np

In [ ]:
initial_array = np.array([1,2,3,4,5,6,7,8,9,10])
print("type of initial_array: ", type(initial_array)) # here nd array means n dimensional array

second_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(second_array.shape) 
#here it cant be (second_array.shape()) 
# when can call method in 2 way ; 1. using () 2. using . ; we use parenthesis when they are filterable ; for example heads(6)

print("size of second_array: ", second_array.size)
print("size of second_array: ", second_array.size()) # this will give error because we cant put integer in method

type of initial_array:  <class 'numpy.ndarray'>
(2, 5)
size of second_array:  10


TypeError: 'int' object is not callable

In [ ]:
third_array = np.array([[[1,2,3],
                         [4,5,6]],
                        [[7,8,9],
                         [10,11,12]]])

print("shape of third_array: ", third_array.shape) # here (2,2,3) means 2 rows, 2 columns, 3 layers ; if we imagine it as image then height, weidth and depth 
print("size of third_array: ", third_array.size) # we can get size by multiplying shape; here (2,2,3) = 2*2*3 = 12


shape of third_array:  (2, 2, 3)
size of third_array:  12


In [ ]:
# Dummy data

z_data = np.zeros((3,4)) # 3 rows, 4 columns
print(z_data)

print("======================================")

y_data = np.zeros((2,3,4))
print(y_data) 

print("======================================")

z_data = np.ones((3))
print(z_data)

print("======================================")

x_data = np.full((2,3), 5) # here it means 2 rows, 3 columns and fill with 5
print(x_data)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1.]
[[5 5 5]
 [5 5 5]]


In [ ]:
#identity matrix
x = np.eye(5) # here dimension does not matter; always square matrix
print(x) #we use to solve non linear equation to linear equation using this; linear equation is y = mx + c


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
a_data = np.arange(4)
print(a_data)

b_data = np.arange(4,4)
print(b_data)

c_data = np.arange(4,4.5,0.2)
print(c_data)

[0 1 2 3]
[]
[4.  4.2 4.4]


In [8]:
#linspace ; used for evenly spaced values between two values
a = np.linspace(1.94, 2)
print(a) #evenly spaced values between two values
b = np.linspace(1, 2, 5)
print(b) #5 evenly spaced values between 1 and 2
c = np.linspace(1, 3,4)
print(c)
d = np.array(np.arange(2,40,4))  
print(d)


[1.94       1.94122449 1.94244898 1.94367347 1.94489796 1.94612245
 1.94734694 1.94857143 1.94979592 1.95102041 1.9522449  1.95346939
 1.95469388 1.95591837 1.95714286 1.95836735 1.95959184 1.96081633
 1.96204082 1.96326531 1.9644898  1.96571429 1.96693878 1.96816327
 1.96938776 1.97061224 1.97183673 1.97306122 1.97428571 1.9755102
 1.97673469 1.97795918 1.97918367 1.98040816 1.98163265 1.98285714
 1.98408163 1.98530612 1.98653061 1.9877551  1.98897959 1.99020408
 1.99142857 1.99265306 1.99387755 1.99510204 1.99632653 1.99755102
 1.99877551 2.        ]
[1.   1.25 1.5  1.75 2.  ]
[1.         1.66666667 2.33333333 3.        ]
[ 2  6 10 14 18 22 26 30 34 38]


In [12]:
print(d)
print(d[5])
print(d[2:4])
print(d[2:])
print(d[:4])
print(d[1:5:2]) # here 1:5:2 means 1,3
print(d[5, : ]) # cant happen because 1 dimensional array

[ 2  6 10 14 18 22 26 30 34 38]
22
[10 14]
[10 14 18 22 26 30 34 38]
[ 2  6 10 14]
[ 6 14]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [18]:
e = np.array([np.arange(2,40,4), np.arange(3,41,4)])
print(e)
print(e[1, : ]) #here it means 2nd row
print(e[:, 1]) #here it means 2nd column

[[ 2  6 10 14 18 22 26 30 34 38]
 [ 3  7 11 15 19 23 27 31 35 39]]
[ 3  7 11 15 19 23 27 31 35 39]
[6 7]


In [29]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a2 = np.array([11,12,13,14,15,16,17,18,19,20])
a3 = [1,5,9]

print(a1 + a2)
print(a1**a2)
print(np.dot(a1,a2))
print(np.mean(a1))
print(np.sum(a1))
print(np.min(a1))

print(a2>18)

print(a2[a3])

[12 14 16 18 20 22 24 26 28 30]
[          1        4096     1594323   268435456   452807053  -683606016
 -2094633337           0  -400556711  1661992960]
935
5.5
55
1
[False False False False False False False False  True  True]
[12 16 20]


In [44]:
random_data = np.random.randint((2,9))
print(random_data)

random_data2 = np.random.randint(2,9)
print(random_data2)

random_data3 = np.random.randint(2,9, size=(3,3))
print(random_data3)

print("======================================")

random_data4 = np.random.randint(2,9, size=(2,2,4))
print(random_data4)

print("======================================")


random_data5 = np.random.rand(2,2,4)
print(random_data5)

print("======================================")

print(np.sort(random_data5))

print("======================================")

random_data6 = np.random.randn(1, 4) #normal or gaussian distribution
print(random_data6)

print("======================================")


[1 4]
3
[[7 2 4]
 [3 8 7]
 [7 2 7]]
[[[3 8 4 5]
  [3 7 3 4]]

 [[4 5 2 6]
  [8 6 4 3]]]
[[[0.4849916  0.1547461  0.13346027 0.98840856]
  [0.72865133 0.16456441 0.19483688 0.49221457]]

 [[0.65070462 0.33809396 0.92783206 0.50990204]
  [0.43374715 0.31031906 0.87086528 0.75261602]]]
[[[0.13346027 0.1547461  0.4849916  0.98840856]
  [0.16456441 0.19483688 0.49221457 0.72865133]]

 [[0.33809396 0.50990204 0.65070462 0.92783206]
  [0.31031906 0.43374715 0.75261602 0.87086528]]]
[[ 1.33311772 -0.92277142 -0.49385327  0.62068472]]
